Repository Ward-Group/Ward_Server, pull requests merged in 2024-06, with the labels that each got.

#43 feature: 닉네임 조회+닉네임 수정 기능
  src/main/java/com/ward/ward_server/api/user/controller/AuthController.java
  src/main/java/com/ward/ward_server/api/user/controller/UserController.java
  src/main/java/com/ward/ward_server/api/user/entity/User.java
  src/main/java/com/ward/ward_server/api/user/repository/UserRepository.java
  src/main/java/com/ward/ward_server/api/user/service/UserService.java
  src/main/java/com/ward/ward_server/global/response/ApiResponseMessage.java
Labels: enhancement

#44 refactor: SocialLogin.java 에서 @Table, @Column 어노테이션 삭제
  src/main/java/com/ward/ward_server/api/user/entity/SocialLogin.java
Labels: enhancement

#46 Refactor/auth refactor
  src/main/java/com/ward/ward_server/api/user/controller/AuthController.java
  src/main/java/com/ward/ward_server/api/user/service/AuthService.java
Labels: enhancement

#47 Refactor/auth refactor
  src/main/java/com/ward/ward_server/api/user/service/AuthService.java
  src/main/java/com/ward/ward_server/global/exception/ExceptionCode.java
Labels: enhancement

#48 refactor: 토큰 갱신 메서드 예외처리 추가
  src/main/java/com/ward/ward_server/api/user/service/AuthService.java
  src/main/java/com/ward/ward_server/global/exception/ExceptionCode.java
Labels: enhancement

#50 fix: 회원가입 시 providerId 길이로 인한 실패 해결
  src/main/java/com/ward/ward_server/api/user/entity/SocialLogin.java
Labels: enhancement

#51 refactor: dto 클래스->record 로 변경
  src/main/java/com/ward/ward_server/api/user/controller/AppleUserController.java
  src/main/java/com/ward/ward_server/api/user/controller/AuthController.java
  src/main/java/com/ward/ward_server/api/user/dto/AddSocialLoginRequest.java
  src/main/java/com/ward/ward_server/api/user/dto/LoginRequest.java
  src/main/java/com/ward/ward_server/api/user/dto/RegisterRequest.java
  src/main/java/com/ward/ward_server/api/user/dto/UserInfoUpdateRequest.java
  src/main/java/com/ward/ward_server/api/user/service/AuthService.java
Labels: enhancement

#53 feature: 애플 로그인에서 2번째 로그인부터 이메일 제공 안함에 따른 로그인 로직 변경
  src/main/java/com/ward/ward_server/api/user/entity/SocialLogin.java
  src/main/java/com/ward/ward_server/api/user/repository/SocialLoginRepository.java
  src/main/java/com/ward/ward_server/api/user/service/AuthService.java
  src/main/java/com/ward/ward_server/global/Object/Constants.java
  src/main/java/com/ward/ward_server/global/exception/ExceptionCode.java
Labels: enhancement

#54 refactor: 예외 처리 구체화-access, refresh 토큰
  src/main/java/com/ward/ward_server/api/user/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/ward/ward_server/api/user/auth/security/JwtDecoder.java
  src/main/java/com/ward/ward_server/api/user/auth/security/UnauthorizedHandler.java
  src/main/java/com/ward/ward_server/api/user/service/AuthService.java
  src/main/java/com/ward/ward_server/global/config/WebSecurityConfig.java
  src/main/java/com/ward/ward_server/global/exception/ExceptionCode.java
Labels: enhancement

#56 Feature/recommended brands api
  src/main/java/com/ward/ward_server/api/item/controller/BrandController.java
  src/main/java/com/ward/ward_server/api/item/dto/BrandRecommendedResponse.java
  src/main/java/com/ward/ward_server/api/item/repository/BrandRepository.java
  src/main/java/com/ward/ward_server/api/item/service/BrandService.java
  src/main/java/com/ward/ward_server/global/config/WebSecurityConfig.java
  src/main/java/com/ward/ward_server/global/response/ApiResponseMessage.java
  src/test/java/com/ward/ward_server/api/item/service/BrandServiceTest.java
Labels: enhancement

#57 매 정각 상품 조회순 Top10 조회 API 개발
  src/main/java/com/ward/ward_server/api/item/controller/ItemController.java
  src/main/java/com/ward/ward_server/api/item/dto/ItemTop10Response.java
  src/main/java/com/ward/ward_server/api/item/entity/ItemViewCount.java
  src/main/java/com/ward/ward_server/api/item/repository/ItemViewCountRepository.java
  src/main/java/com/ward/ward_server/api/item/scheduler/ItemViewCountScheduler.java
  src/main/java/com/ward/ward_server/api/item/service/ItemService.java
  src/main/java/com/ward/ward_server/api/item/service/TopItemsCacheService.java
  src/main/java/com/ward/ward_server/global/config/WebSecurityConfig.java
  src/main/java/com/ward/ward_server/global/response/ApiResponseMessage.java
Labels: enhancement

#62 Feature/item detail page api
  .gitignore
  src/main/java/com/ward/ward_server/api/item/controller/ItemController.java
  src/main/java/com/ward/ward_server/api/item/dto/ItemDetailResponse.java
  src/main/java/com/ward/ward_server/api/item/repository/ItemRepository.java
  src/main/java/com/ward/ward_server/api/item/service/ItemService.java
  src/main/java/com/ward/ward_server/api/releaseInfo/controller/ReleaseInfoController.java
  src/main/java/com/ward/ward_server/api/releaseInfo/repository/ReleaseInfoRepository.java
  src/main/java/com/ward/ward_server/api/releaseInfo/service/ReleaseInfoService.java
  src/main/java/com/ward/ward_server/global/config/WebSecurityConfig.java
  src/main/java/com/ward/ward_server/global/exception/handler/ExceptionHandler.java
  src/main/java/com/ward/ward_server/global/response/error/ErrorCode.java
  src/test/java/com/ward/ward_server/api/releaseInfo/service/ReleaseInfoServiceTest.java
Labels: enhancement

#63 feature: <검색 화면> - 검색 기록 조회 API 개발
  src/main/java/com/ward/ward_server/api/search/controller/SearchHistoryController.java
  src/main/java/com/ward/ward_server/api/search/entity/SearchHistory.java
  src/main/java/com/ward/ward_server/api/search/repository/SearchHistoryRepository.java
  src/main/java/com/ward/ward_server/api/search/service/SearchHistoryService.java
Labels: enhancement

#65 Refactor: ErrorCode -> ErrorMessage / Sort -> HomeSort 이름 변경
  src/main/java/com/ward/ward_server/api/item/controller/ItemController.java
  src/main/java/com/ward/ward_server/api/item/entity/enums/Category.java
  src/main/java/com/ward/ward_server/api/item/service/BrandService.java
  src/main/java/com/ward/ward_server/api/item/service/ItemService.java
  src/main/java/com/ward/ward_server/api/releaseInfo/controller/ReleaseInfoController.java
  src/main/java/com/ward/ward_server/api/releaseInfo/entity/enums/CurrencyUnit.java
  src/main/java/com/ward/ward_server/api/releaseInfo/entity/enums/DeliveryMethod.java
  src/main/java/com/ward/ward_server/api/releaseInfo/entity/enums/NotificationMethod.java
  src/main/java/com/ward/ward_server/api/releaseInfo/entity/enums/ReleaseMethod.java
  src/main/java/com/ward/ward_server/api/releaseInfo/service/DrawPlatformService.java
  src/main/java/com/ward/ward_server/api/releaseInfo/service/ReleaseInfoService.java
  src/main/java/com/ward/ward_server/global/Object/enums/ApiSort.java
  src/main/java/com/ward/ward_server/global/Object/enums/HomeSort.java
  src/main/java/com/ward/ward_server/global/Object/enums/converter/HomeSortControllerAdvice.java
  src/main/java/com/ward/ward_server/global/Object/enums/converter/HomeSortConverter.java
  src/main/java/com/ward/ward_server/global/Object/enums/converter/SortConverter.java
  src/main/java/com/ward/ward_server/global/config/WebMvcConfig.java
  src/main/java/com/ward/ward_server/global/exception/handler/ExceptionHandler.java
  src/main/java/com/ward/ward_server/global/response/ApiResponse.java
  src/main/java/com/ward/ward_server/global/response/error/ErrorMessage.java
  src/main/java/com/ward/ward_server/global/util/ValidationUtils.java
  src/test/java/com/ward/ward_server/api/item/entity/enumtype/HomeSortTest.java
  src/test/java/com/ward/ward_server/api/item/entity/enumtype/SortTest.java
Labels: refactor

#67 검색 기록 기능 삭제 + 상품 검색 API 개발
  src/main/java/com/ward/ward_server/api/item/repository/ItemRepository.java
  src/main/java/com/ward/ward_server/api/releaseInfo/repository/ReleaseInfoRepository.java
  src/main/java/com/ward/ward_server/api/search/controller/SearchController.java
  src/main/java/com/ward/ward_server/api/search/controller/SearchHistoryController.java
  src/main/java/com/ward/ward_server/api/search/dto/SearchItemsResponse.java
  src/main/java/com/ward/ward_server/api/search/entity/SearchHistory.java
  src/main/java/com/ward/ward_server/api/search/repository/SearchHistoryRepository.java
  src/main/java/com/ward/ward_server/api/search/service/SearchHistoryService.java
  src/main/java/com/ward/ward_server/api/search/service/SearchService.java
  src/test/java/com/ward/ward_server/api/search/service/SearchServiceTest.java
Labels: enhancement

#70 feat: 인증 및 예외 처리 개선
  src/main/java/com/ward/ward_server/api/user/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/ward/ward_server/api/user/auth/security/UnauthorizedHandler.java
  src/main/java/com/ward/ward_server/global/config/WebSecurityConfig.java
  src/main/java/com/ward/ward_server/global/exception/handler/ExceptionHandler.java
Labels: enhancement

#74 Feat: 카테고리별, 정렬별 상품 목록/페이지 조회 API
  src/main/java/com/ward/ward_server/api/item/controller/ItemController.java
  src/main/java/com/ward/ward_server/api/item/dto/ItemSimpleResponse.java
  src/main/java/com/ward/ward_server/api/item/repository/query/ItemQueryRepository.java
  src/main/java/com/ward/ward_server/api/item/repository/query/ItemQueryRepositoryImpl.java
  src/main/java/com/ward/ward_server/api/item/service/ItemService.java
  src/main/java/com/ward/ward_server/global/config/WebSecurityConfig.java
  src/test/java/com/ward/ward_server/api/item/repository/ItemRepositoryTest.java
Labels: refactor, feature, fix

#76 Feat: not found 예외처리 구현
  src/main/java/com/ward/ward_server/global/exception/handler/ExceptionHandler.java
  src/main/java/com/ward/ward_server/global/response/error/ErrorMessage.java
Labels: feature
